### ISSUE TITLE
Fix: 프로젝트 오류 수정

### ISSUE THREAD

**Issue by sieunnnn** [planner-project/sieunLab#12]
# TODO
- [ ] 플래너, 데이트, 플랜 CRUD 시 데이터 부정합 이슈 수정
- [ ] 그룹 멤버 CRUD 시 데이터 부정합 이슈 수정
- [ ] 친구 기능 일부 오류 수정
- [x] vercel 연결 수정
