### ISSUE TITLE
Feat: 이메일 인증 기능 구현

### ISSUE THREAD

**Issue by sieunnnn** [planner-project/sieunLab#3]
# TODO
- [x] 토큰 종류 추가
- [x] 이메일 인증 기능 구현
- [x] 이메일 인증 기능 테스트
